[prompts]
  prefixes = []
  suffixes = [
    "in the style of Picasso",
    "in the style of Tron",
    "in the style of Anime",
    "in the style of Banksy",
    "in a pixel art style",
    "in an isometric 3D style",
    "in a wireframe model style",
    "in the style of Bollywood",
    "in neon colours",
    "in halftone style"
  ]
  negative = ""

[inputs]
  [inputs.openwebif]
  url = "http://vuduo.local"

[replicate]
  model = "cloneofsimo/lora"
  model_version = "fce477182f407ffd66b94b08e761424cabd13b82b518754b83080bc75ad32466"
  [replicate.output]
    width = 1024
    height = 128
  
[output]
  path = "output"
  prefix = "artyfarty"
  timestamp = true
