[prompts]
  prefixes = [
    "hello"
  ]
  suffixes = [
    "in style of picasso"
  ]
  negative = ""

[inputs]
  [inputs.openwebif]
  url = "http://vuduo.home.ptre.es"

[replicate]
  model = "cloneofsimo/lora"
  model_version = "fce477182f407ffd66b94b08e761424cabd13b82b518754b83080bc75ad32466"
  [replicate.output]
    width = 1024
    height = 128
  
[output]
  path = "output"
  prefix = "artyfarty"
  timestamp = true
