[prompts]
  prefixes = [
    
  ]
  suffixes = [
    "in the style of Picasso",
    "in the style of Tron",
    "in the style of Anime",
    "in the style of Banksy",
    "in a pixel art style",
    "in an isometric 3D style",
    "in a wireframe model style",
    "in the style of Bollywood",
    "in neon colours",
    "in halftone style",
    "in dystopian future style",
    "with random animals",
    "in the style of a 1990s video game",
    "in 3D raytraced style",
    "set in America",
    "set in Europe",
    "using Rainbow colours",
    "as a pencil sketch",
    "as an oil painting",
    "tiled and repeated",
    "as Pokemon",
    "as The Simpsons characters",
    "set in Star Trek universe",
    "Star Wars themed"
  ]
  negative = ""

[inputs]
  [inputs.openwebif]
  url = "http://vuduo.home.ptre.es"

[replicate]
  model = "cloneofsimo/lora"
  model_version = "fce477182f407ffd66b94b08e761424cabd13b82b518754b83080bc75ad32466"
  [replicate.output]
    width = 1024
    height = 128
  
[output]
  path = "/opt/wideboy/images/backgrounds"
  prefix = "artyfarty"
  timestamp = true
